
const twTheme: Record<string, any> = {
  colors: {
    inherit: 'colors.inherit',
    current: 'colors.current',
    transparent: 'colors.transparent',
    black: 'colors.black',
    white: 'colors.white',
    slate: 'colors.slate',
    gray: 'colors.gray',
    zinc: 'colors.zinc',
    neutral: 'colors.neutral',
    stone: 'colors.stone',
    red: 'colors.red',
    orange: 'colors.orange',
    amber: 'colors.amber',
    yellow: 'colors.yellow',
    lime: 'colors.lime',
    green: 'colors.green',
    emerald: 'colors.emerald',
    teal: 'colors.teal',
    cyan: 'colors.cyan',
    sky: 'colors.sky',
    blue: 'colors.blue',
    indigo: 'colors.indigo',
    violet: 'colors.violet',
    purple: 'colors.purple',
    fuchsia: 'colors.fuchsia',
    pink: 'colors.pink',
    rose: 'colors.rose',
  },
  columns: {
    auto: 'auto',
    1: '1',
    2: '2',
    3: '3',
    4: '4',
    5: '5',
    6: '6',
    7: '7',
    8: '8',
    9: '9',
    10: '10',
    11: '11',
    12: '12',
    // '3xs': '16rem',
    // '2xs': '18rem',
    // 'xs': '20rem',
    // 'sm': '24rem',
    // 'md': '28rem',
    // 'lg': '32rem',
    // 'xl': '36rem',
    // '2xl': '42rem',
    // '3xl': '48rem',
    // '4xl': '56rem',
    // '5xl': '64rem',
    // '6xl': '72rem',
    // '7xl': '80rem',
  },
  spacing: {
    px: '1px',
    0: '0px',
    0.5: '0.125rem',
    1: '0.25rem',
    1.5: '0.375rem',
    2: '0.5rem',
    2.5: '0.625rem',
    3: '0.75rem',
    3.5: '0.875rem',
    4: '1rem',
    5: '1.25rem',
    6: '1.5rem',
    7: '1.75rem',
    8: '2rem',
    9: '2.25rem',
    10: '2.5rem',
    11: '2.75rem',
    12: '3rem',
    14: '3.5rem',
    16: '4rem',
    20: '5rem',
    24: '6rem',
    28: '7rem',
    32: '8rem',
    36: '9rem',
    40: '10rem',
    44: '11rem',
    48: '12rem',
    52: '13rem',
    56: '14rem',
    60: '15rem',
    64: '16rem',
    72: '18rem',
    80: '20rem',
    96: '24rem',
  },
  animation: {
    none: 'none',
    spin: 'spin 1s linear infinite',
    ping: 'ping 1s cubic-bezier(0, 0, 0.2, 1) infinite',
    pulse: 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
    bounce: 'bounce 1s infinite',
  },
  aspectRatio: {
    auto: 'auto',
    square: '1 / 1',
    video: '16 / 9',
  },
  backdropBlur: ({ theme }: any) => theme('blur'),
  backdropBrightness: ({ theme }: any) => theme('brightness'),
  backdropContrast: ({ theme }: any) => theme('contrast'),
  backdropGrayscale: ({ theme }: any) => theme('grayscale'),
  backdropHueRotate: ({ theme }: any) => theme('hueRotate'),
  backdropInvert: ({ theme }: any) => theme('invert'),
  backdropOpacity: ({ theme }: any) => theme('opacity'),
  backdropSaturate: ({ theme }: any) => theme('saturate'),
  backdropSepia: ({ theme }: any) => theme('sepia'),
  backgroundColor: ({ theme }: any) => theme('colors'),
  backgroundImage: {
    'none': 'none',
    'gradient-to-t': 'linear-gradient(to top, var(--tw-gradient-stops))',
    'gradient-to-tr': 'linear-gradient(to top right, var(--tw-gradient-stops))',
    'gradient-to-r': 'linear-gradient(to right, var(--tw-gradient-stops))',
    'gradient-to-br': 'linear-gradient(to bottom right, var(--tw-gradient-stops))',
    'gradient-to-b': 'linear-gradient(to bottom, var(--tw-gradient-stops))',
    'gradient-to-bl': 'linear-gradient(to bottom left, var(--tw-gradient-stops))',
    'gradient-to-l': 'linear-gradient(to left, var(--tw-gradient-stops))',
    'gradient-to-tl': 'linear-gradient(to top left, var(--tw-gradient-stops))',
  },
  backgroundOpacity: ({ theme }: any) => theme('opacity'),
  backgroundPosition: {
    'bottom': 'bottom',
    'center': 'center',
    'left': 'left',
    'left-bottom': 'left bottom',
    'left-top': 'left top',
    'right': 'right',
    'right-bottom': 'right bottom',
    'right-top': 'right top',
    'top': 'top',
  },
  backgroundSize: {
    auto: 'auto',
    cover: 'cover',
    contain: 'contain',
  },
  blur: {
    '0': '0',
    'none': '0',
    'sm': '4px',
    'DEFAULT': '8px',
    'md': '12px',
    'lg': '16px',
    'xl': '24px',
    '2xl': '40px',
    '3xl': '64px',
  },
  brightness: {
    0: '0',
    50: '.5',
    75: '.75',
    90: '.9',
    95: '.95',
    100: '1',
    105: '1.05',
    110: '1.1',
    125: '1.25',
    150: '1.5',
    200: '2',
  },
  borderColor: ({ theme }: any) => ({
    ...theme('colors'),
    DEFAULT: theme('colors.gray.200', 'currentColor'),
  }),
  borderOpacity: ({ theme }: any) => theme('opacity'),
  borderRadius: {
    'none': '0px',
    'sm': '0.125rem',
    'DEFAULT': '0.25rem',
    'md': '0.375rem',
    'lg': '0.5rem',
    'xl': '0.75rem',
    '2xl': '1rem',
    '3xl': '1.5rem',
    'full': '9999px',
  },
  borderWidth: {
    DEFAULT: '1px',
    0: '0px',
    2: '2px',
    4: '4px',
    8: '8px',
  },
  boxShadow: {
    'sm': '0 1px 2px 0 rgb(0 0 0 / 0.05)',
    'DEFAULT': '0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)',
    'md': '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)',
    'lg': '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)',
    'xl': '0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)',
    '2xl': '0 25px 50px -12px rgb(0 0 0 / 0.25)',
    'inner': 'inset 0 2px 4px 0 rgb(0 0 0 / 0.05)',
    'none': 'none',
  },
  boxShadowColor: ({ theme }: any) => theme('colors'),
  caretColor: ({ theme }: any) => theme('colors'),
  accentColor: ({ theme }: any) => ({
    ...theme('colors'),
    auto: 'auto',
  }),
  contrast: {
    0: '0',
    50: '.5',
    75: '.75',
    100: '1',
    125: '1.25',
    150: '1.5',
    200: '2',
  },
  container: {},
  content: {
    none: 'none',
  },
  cursor: {
    'auto': 'auto',
    'default': 'default',
    'pointer': 'pointer',
    'wait': 'wait',
    'text': 'text',
    'move': 'move',
    'help': 'help',
    'not-allowed': 'not-allowed',
    'none': 'none',
    'context-menu': 'context-menu',
    'progress': 'progress',
    'cell': 'cell',
    'crosshair': 'crosshair',
    'vertical-text': 'vertical-text',
    'alias': 'alias',
    'copy': 'copy',
    'no-drop': 'no-drop',
    'grab': 'grab',
    'grabbing': 'grabbing',
    'all-scroll': 'all-scroll',
    'col-resize': 'col-resize',
    'row-resize': 'row-resize',
    'n-resize': 'n-resize',
    'e-resize': 'e-resize',
    's-resize': 's-resize',
    'w-resize': 'w-resize',
    'ne-resize': 'ne-resize',
    'nw-resize': 'nw-resize',
    'se-resize': 'se-resize',
    'sw-resize': 'sw-resize',
    'ew-resize': 'ew-resize',
    'ns-resize': 'ns-resize',
    'nesw-resize': 'nesw-resize',
    'nwse-resize': 'nwse-resize',
    'zoom-in': 'zoom-in',
    'zoom-out': 'zoom-out',
  },
  divideColor: ({ theme }: any) => theme('borderColor'),
  divideOpacity: ({ theme }: any) => theme('borderOpacity'),
  divideWidth: ({ theme }: any) => theme('borderWidth'),
  dropShadow: {
    'sm': '0 1px 1px rgb(0 0 0 / 0.05)',
    'DEFAULT': ['0 1px 2px rgb(0 0 0 / 0.1)', '0 1px 1px rgb(0 0 0 / 0.06)'],
    'md': ['0 4px 3px rgb(0 0 0 / 0.07)', '0 2px 2px rgb(0 0 0 / 0.06)'],
    'lg': ['0 10px 8px rgb(0 0 0 / 0.04)', '0 4px 3px rgb(0 0 0 / 0.1)'],
    'xl': ['0 20px 13px rgb(0 0 0 / 0.03)', '0 8px 5px rgb(0 0 0 / 0.08)'],
    '2xl': '0 25px 25px rgb(0 0 0 / 0.15)',
    'none': '0 0 #0000',
  },
  fill: ({ theme }: any) => theme('colors'),
  grayscale: {
    0: '0',
    DEFAULT: '100%',
  },
  hueRotate: {
    0: '0deg',
    15: '15deg',
    30: '30deg',
    60: '60deg',
    90: '90deg',
    180: '180deg',
  },
  invert: {
    0: '0',
    DEFAULT: '100%',
  },
  flex: {
    1: '1 1 0%',
    auto: '1 1 auto',
    initial: '0 1 auto',
    none: 'none',
  },
  flexBasis: ({ theme }: any) => ({
    'auto': 'auto',
    ...theme('spacing'),
    '1/2': '50%',
    '1/3': '33.333333%',
    '2/3': '66.666667%',
    '1/4': '25%',
    '2/4': '50%',
    '3/4': '75%',
    '1/5': '20%',
    '2/5': '40%',
    '3/5': '60%',
    '4/5': '80%',
    '1/6': '16.666667%',
    '2/6': '33.333333%',
    '3/6': '50%',
    '4/6': '66.666667%',
    '5/6': '83.333333%',
    '1/12': '8.333333%',
    '2/12': '16.666667%',
    '3/12': '25%',
    '4/12': '33.333333%',
    '5/12': '41.666667%',
    '6/12': '50%',
    '7/12': '58.333333%',
    '8/12': '66.666667%',
    '9/12': '75%',
    '10/12': '83.333333%',
    '11/12': '91.666667%',
    'full': '100%',
  }),
  flexGrow: {
    0: '0',
    DEFAULT: '1',
  },
  flexShrink: {
    0: '0',
    DEFAULT: '1',
  },
  fontFamily: {
    sans: [
      'ui-sans-serif',
      'system-ui',
      '-apple-system',
      'BlinkMacSystemFont',
      '"Segoe UI"',
      'Roboto',
      '"Helvetica Neue"',
      'Arial',
      '"Noto Sans"',
      'sans-serif',
      '"Apple Color Emoji"',
      '"Segoe UI Emoji"',
      '"Segoe UI Symbol"',
      '"Noto Color Emoji"',
    ],
    serif: ['ui-serif', 'Georgia', 'Cambria', '"Times New Roman"', 'Times', 'serif'],
    mono: [
      'ui-monospace',
      'SFMono-Regular',
      'Menlo',
      'Monaco',
      'Consolas',
      '"Liberation Mono"',
      '"Courier New"',
      'monospace',
    ],
  },
  fontSize: {
    'xs': ['0.75rem', { lineHeight: '1rem' }],
    'sm': ['0.875rem', { lineHeight: '1.25rem' }],
    'base': ['1rem', { lineHeight: '1.5rem' }],
    'lg': ['1.125rem', { lineHeight: '1.75rem' }],
    'xl': ['1.25rem', { lineHeight: '1.75rem' }],
    '2xl': ['1.5rem', { lineHeight: '2rem' }],
    '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
    '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
    '5xl': ['3rem', { lineHeight: '1' }],
    '6xl': ['3.75rem', { lineHeight: '1' }],
    '7xl': ['4.5rem', { lineHeight: '1' }],
    '8xl': ['6rem', { lineHeight: '1' }],
    '9xl': ['8rem', { lineHeight: '1' }],
  },
  fontWeight: {
    thin: '100',
    extralight: '200',
    light: '300',
    normal: '400',
    medium: '500',
    semibold: '600',
    bold: '700',
    extrabold: '800',
    black: '900',
  },
  gap: ({ theme }: any) => theme('spacing'),
  gradientColorStops: ({ theme }: any) => theme('colors'),
  gridAutoColumns: {
    auto: 'auto',
    min: 'min-content',
    max: 'max-content',
    fr: 'minmax(0, 1fr)',
  },
  gridAutoRows: {
    auto: 'auto',
    min: 'min-content',
    max: 'max-content',
    fr: 'minmax(0, 1fr)',
  },
  gridColumn: {
    'auto': 'auto',
    'span-1': 'span 1 / span 1',
    'span-2': 'span 2 / span 2',
    'span-3': 'span 3 / span 3',
    'span-4': 'span 4 / span 4',
    'span-5': 'span 5 / span 5',
    'span-6': 'span 6 / span 6',
    'span-7': 'span 7 / span 7',
    'span-8': 'span 8 / span 8',
    'span-9': 'span 9 / span 9',
    'span-10': 'span 10 / span 10',
    'span-11': 'span 11 / span 11',
    'span-12': 'span 12 / span 12',
    'span-full': '1 / -1',
  },
  gridColumnEnd: {
    auto: 'auto',
    1: '1',
    2: '2',
    3: '3',
    4: '4',
    5: '5',
    6: '6',
    7: '7',
    8: '8',
    9: '9',
    10: '10',
    11: '11',
    12: '12',
    13: '13',
  },
  gridColumnStart: {
    auto: 'auto',
    1: '1',
    2: '2',
    3: '3',
    4: '4',
    5: '5',
    6: '6',
    7: '7',
    8: '8',
    9: '9',
    10: '10',
    11: '11',
    12: '12',
    13: '13',
  },
  gridRow: {
    'auto': 'auto',
    'span-1': 'span 1 / span 1',
    'span-2': 'span 2 / span 2',
    'span-3': 'span 3 / span 3',
    'span-4': 'span 4 / span 4',
    'span-5': 'span 5 / span 5',
    'span-6': 'span 6 / span 6',
    'span-full': '1 / -1',
  },
  gridRowStart: {
    auto: 'auto',
    1: '1',
    2: '2',
    3: '3',
    4: '4',
    5: '5',
    6: '6',
    7: '7',
  },
  gridRowEnd: {
    auto: 'auto',
    1: '1',
    2: '2',
    3: '3',
    4: '4',
    5: '5',
    6: '6',
    7: '7',
  },
  gridTemplateColumns: {
    none: 'none',
    1: 'repeat(1, minmax(0, 1fr))',
    2: 'repeat(2, minmax(0, 1fr))',
    3: 'repeat(3, minmax(0, 1fr))',
    4: 'repeat(4, minmax(0, 1fr))',
    5: 'repeat(5, minmax(0, 1fr))',
    6: 'repeat(6, minmax(0, 1fr))',
    7: 'repeat(7, minmax(0, 1fr))',
    8: 'repeat(8, minmax(0, 1fr))',
    9: 'repeat(9, minmax(0, 1fr))',
    10: 'repeat(10, minmax(0, 1fr))',
    11: 'repeat(11, minmax(0, 1fr))',
    12: 'repeat(12, minmax(0, 1fr))',
  },
  gridTemplateRows: {
    none: 'none',
    1: 'repeat(1, minmax(0, 1fr))',
    2: 'repeat(2, minmax(0, 1fr))',
    3: 'repeat(3, minmax(0, 1fr))',
    4: 'repeat(4, minmax(0, 1fr))',
    5: 'repeat(5, minmax(0, 1fr))',
    6: 'repeat(6, minmax(0, 1fr))',
  },
  height: ({ theme }: any) => ({
    'auto': 'auto',
    ...theme('spacing'),
    '1/2': '50%',
    '1/3': '33.333333%',
    '2/3': '66.666667%',
    '1/4': '25%',
    '2/4': '50%',
    '3/4': '75%',
    '1/5': '20%',
    '2/5': '40%',
    '3/5': '60%',
    '4/5': '80%',
    '1/6': '16.666667%',
    '2/6': '33.333333%',
    '3/6': '50%',
    '4/6': '66.666667%',
    '5/6': '83.333333%',
    'full': '100%',
    'screen': '100vh',
    'min': 'min-content',
    'max': 'max-content',
    'fit': 'fit-content',
  }),
  inset: ({ theme }: any) => ({
    'auto': 'auto',
    ...theme('spacing'),
    '1/2': '50%',
    '1/3': '33.333333%',
    '2/3': '66.666667%',
    '1/4': '25%',
    '2/4': '50%',
    '3/4': '75%',
    'full': '100%',
  }),
  keyframes: {
    spin: {
      to: {
        transform: 'rotate(360deg)',
      },
    },
    ping: {
      '75%, 100%': {
        transform: 'scale(2)',
        opacity: '0',
      },
    },
    pulse: {
      '50%': {
        opacity: '.5',
      },
    },
    bounce: {
      '0%, 100%': {
        transform: 'translateY(-25%)',
        animationTimingFunction: 'cubic-bezier(0.8,0,1,1)',
      },
      '50%': {
        transform: 'none',
        animationTimingFunction: 'cubic-bezier(0,0,0.2,1)',
      },
    },
  },
  letterSpacing: {
    tighter: '-0.05em',
    tight: '-0.025em',
    normal: '0em',
    wide: '0.025em',
    wider: '0.05em',
    widest: '0.1em',
  },
  lineHeight: {
    none: '1',
    tight: '1.25',
    snug: '1.375',
    normal: '1.5',
    relaxed: '1.625',
    loose: '2',
    3: '.75rem',
    4: '1rem',
    5: '1.25rem',
    6: '1.5rem',
    7: '1.75rem',
    8: '2rem',
    9: '2.25rem',
    10: '2.5rem',
  },
  listStyleType: {
    none: 'none',
    disc: 'disc',
    decimal: 'decimal',
  },
  margin: ({ theme }: any) => ({
    auto: 'auto',
    ...theme('spacing'),
  }),
  maxHeight: ({ theme }: any) => ({
    ...theme('spacing'),
    full: '100%',
    screen: '100vh',
    min: 'min-content',
    max: 'max-content',
    fit: 'fit-content',
  }),
  maxWidth: (/* { theme }: any */) => ({
    'none': 'none',
    '0': '0rem',
    'xs': '20rem',
    'sm': '24rem',
    'md': '28rem',
    'lg': '32rem',
    'xl': '36rem',
    '2xl': '42rem',
    '3xl': '48rem',
    '4xl': '56rem',
    '5xl': '64rem',
    '6xl': '72rem',
    '7xl': '80rem',
    'full': '100%',
    'min': 'min-content',
    'max': 'max-content',
    'fit': 'fit-content',
    'prose': '65ch',
  }),
  minHeight: {
    0: '0px',
    full: '100%',
    screen: '100vh',
    min: 'min-content',
    max: 'max-content',
    fit: 'fit-content',
  },
  minWidth: {
    0: '0px',
    full: '100%',
    min: 'min-content',
    max: 'max-content',
    fit: 'fit-content',
  },
  objectPosition: {
    'bottom': 'bottom',
    'center': 'center',
    'left': 'left',
    'left-bottom': 'left bottom',
    'left-top': 'left top',
    'right': 'right',
    'right-bottom': 'right bottom',
    'right-top': 'right top',
    'top': 'top',
  },
  opacity: {
    0: '0',
    5: '0.05',
    10: '0.1',
    20: '0.2',
    25: '0.25',
    30: '0.3',
    40: '0.4',
    50: '0.5',
    60: '0.6',
    70: '0.7',
    75: '0.75',
    80: '0.8',
    90: '0.9',
    95: '0.95',
    100: '1',
  },
  order: {
    first: '-9999',
    last: '9999',
    none: '0',
    1: '1',
    2: '2',
    3: '3',
    4: '4',
    5: '5',
    6: '6',
    7: '7',
    8: '8',
    9: '9',
    10: '10',
    11: '11',
    12: '12',
  },
  padding: ({ theme }: any) => theme('spacing'),
  placeholderColor: ({ theme }: any) => theme('colors'),
  placeholderOpacity: ({ theme }: any) => theme('opacity'),
  outlineColor: ({ theme }: any) => theme('colors'),
  outlineOffset: {
    0: '0px',
    1: '1px',
    2: '2px',
    4: '4px',
    8: '8px',
  },
  outlineWidth: {
    0: '0px',
    1: '1px',
    2: '2px',
    4: '4px',
    8: '8px',
  },
  ringColor: ({ theme }: any) => ({
    DEFAULT: theme('colors.blue.500', '#3b82f6'),
    ...theme('colors'),
  }),
  ringOffsetColor: ({ theme }: any) => theme('colors'),
  ringOffsetWidth: {
    0: '0px',
    1: '1px',
    2: '2px',
    4: '4px',
    8: '8px',
  },
  ringOpacity: ({ theme }: any) => ({
    DEFAULT: '0.5',
    ...theme('opacity'),
  }),
  ringWidth: {
    DEFAULT: '3px',
    0: '0px',
    1: '1px',
    2: '2px',
    4: '4px',
    8: '8px',
  },
  rotate: {
    0: '0deg',
    1: '1deg',
    2: '2deg',
    3: '3deg',
    6: '6deg',
    12: '12deg',
    45: '45deg',
    90: '90deg',
    180: '180deg',
  },
  saturate: {
    0: '0',
    50: '.5',
    100: '1',
    150: '1.5',
    200: '2',
  },
  scale: {
    0: '0',
    50: '.5',
    75: '.75',
    90: '.9',
    95: '.95',
    100: '1',
    105: '1.05',
    110: '1.1',
    125: '1.25',
    150: '1.5',
  },
  scrollMargin: ({ theme }: any) => ({
    ...theme('spacing'),
  }),
  scrollPadding: ({ theme }: any) => theme('spacing'),
  sepia: {
    0: '0',
    DEFAULT: '100%',
  },
  skew: {
    0: '0deg',
    1: '1deg',
    2: '2deg',
    3: '3deg',
    6: '6deg',
    12: '12deg',
  },
  space: ({ theme }: any) => ({
    ...theme('spacing'),
  }),
  stroke: ({ theme }: any) => theme('colors'),
  strokeWidth: {
    0: '0',
    1: '1',
    2: '2',
  },
  textColor: ({ theme }: any) => theme('colors'),
  textDecorationColor: ({ theme }: any) => theme('colors'),
  textDecorationThickness: {
    'auto': 'auto',
    'from-font': 'from-font',
    '0': '0px',
    '1': '1px',
    '2': '2px',
    '4': '4px',
    '8': '8px',
  },
  textUnderlineOffset: {
    auto: 'auto',
    0: '0px',
    1: '1px',
    2: '2px',
    4: '4px',
    8: '8px',
  },
  textIndent: ({ theme }: any) => ({
    ...theme('spacing'),
  }),
  textOpacity: ({ theme }: any) => theme('opacity'),
  transformOrigin: {
    'center': 'center',
    'top': 'top',
    'top-right': 'top right',
    'right': 'right',
    'bottom-right': 'bottom right',
    'bottom': 'bottom',
    'bottom-left': 'bottom left',
    'left': 'left',
    'top-left': 'top left',
  },
  transitionDelay: {
    75: '75ms',
    100: '100ms',
    150: '150ms',
    200: '200ms',
    300: '300ms',
    500: '500ms',
    700: '700ms',
    1000: '1000ms',
  },
  transitionDuration: {
    DEFAULT: '150ms',
    75: '75ms',
    100: '100ms',
    150: '150ms',
    200: '200ms',
    300: '300ms',
    500: '500ms',
    700: '700ms',
    1000: '1000ms',
  },
  transitionProperty: {
    none: 'none',
    all: 'all',
    DEFAULT:
      'color, background-color, border-color, text-decoration-color, fill, stroke, opacity, box-shadow, transform, filter, backdrop-filter',
    colors: 'color, background-color, border-color, text-decoration-color, fill, stroke',
    opacity: 'opacity',
    shadow: 'box-shadow',
    transform: 'transform',
  },
  transitionTimingFunction: {
    'DEFAULT': 'cubic-bezier(0.4, 0, 0.2, 1)',
    'linear': 'linear',
    'in': 'cubic-bezier(0.4, 0, 1, 1)',
    'out': 'cubic-bezier(0, 0, 0.2, 1)',
    'in-out': 'cubic-bezier(0.4, 0, 0.2, 1)',
  },
  translate: ({ theme }: any) => ({
    ...theme('spacing'),
    '1/2': '50%',
    '1/3': '33.333333%',
    '2/3': '66.666667%',
    '1/4': '25%',
    '2/4': '50%',
    '3/4': '75%',
    'full': '100%',
  }),
  width: ({ theme }: any) => ({
    'auto': 'auto',
    ...theme('spacing'),
    '1/2': '50%',
    '1/3': '33.333333%',
    '2/3': '66.666667%',
    '1/4': '25%',
    '2/4': '50%',
    '3/4': '75%',
    '1/5': '20%',
    '2/5': '40%',
    '3/5': '60%',
    '4/5': '80%',
    '1/6': '16.666667%',
    '2/6': '33.333333%',
    '3/6': '50%',
    '4/6': '66.666667%',
    '5/6': '83.333333%',
    '1/12': '8.333333%',
    '2/12': '16.666667%',
    '3/12': '25%',
    '4/12': '33.333333%',
    '5/12': '41.666667%',
    '6/12': '50%',
    '7/12': '58.333333%',
    '8/12': '66.666667%',
    '9/12': '75%',
    '10/12': '83.333333%',
    '11/12': '91.666667%',
    'full': '100%',
    'screen': '100vw',
    'min': 'min-content',
    'max': 'max-content',
    'fit': 'fit-content',
  }),
  willChange: {
    auto: 'auto',
    scroll: 'scroll-position',
    contents: 'contents',
    transform: 'transform',
  },
  zIndex: {
    auto: 'auto',
    0: '0',
    10: '10',
    20: '20',
    30: '30',
    40: '40',
    50: '50',
  },
}

const twThemeMapping: ([string] | [string, string[]])[] = [
  ['colors', ['text']],
  ['spacing', ['top', 'right', 'bottom', 'left']],
  ['inset', ['inset', 'inset-x', 'inset-y']],
  ['zIndex', ['z']],
  ['order'],
  ['gridColumn', ['col']],
  ['gridColumnStart', ['col-start']],
  ['gridColumnEnd', ['col-end']],
  ['gridRow', ['row']],
  ['gridRowStart', ['row-start']],
  ['gridRowEnd', ['row-end']],
  ['margin', ['m', 'mx', 'my', 'mt', 'mr', 'mb', 'ml']],
  ['aspectRatio', ['aspect']],
  ['height', ['h']],
  ['maxHeight', ['max-h']],
  ['minHeight', ['min-h']],
  ['width', ['w']],
  ['minWidth', ['min-w']],
  ['maxWidth', ['max-w']],
  ['flex'],
  ['flexShrink', ['flex-shrink', 'shrink']],
  ['flexGrow', ['flex-grow', 'grow']],
  ['flexBasis', ['basis']],
  ['transformOrigin', ['origin']],
  ['translate', ['translate-x', 'translate-y']],
  ['rotate', ['rotate']],
  ['skew', ['skew-x', 'skew-y']],
  ['scale', ['scale', 'scale-x', 'scale-y']],
  ['animation', ['animate']],
  ['cursor'],
  ['scrollMargin', ['scroll-m', 'scroll-mx', 'scroll-my', 'scroll-mt', 'scroll-mr', 'scroll-mb', 'scroll-ml']],
  ['scrollPadding', ['scroll-p', 'scroll-px', 'scroll-py', 'scroll-pt', 'scroll-pr', 'scroll-pb', 'scroll-pl']],
  ['listStyleType', ['list']],
  ['columns', ['columns']],
  ['gridAutoColumns', ['auto-cols']],
  ['gridAutoRows', ['auto-rows']],
  ['gridTemplateColumns', ['grid-cols']],
  ['gridTemplateRows', ['grid-rows']],
  ['gap', ['gap', 'gap-x', 'gap-y']],
  ['space', ['space-x', 'space-y']],
  ['divideWidth', ['divide-x', 'divide-y']],
  ['divideColor', ['divide']],
  ['divideOpacity', ['divide-opacity']],
  ['borderRadius', ['rounded', 'rounded-t', 'rounded-r', 'rounded-b', 'rounded-l', 'rounded-tl', 'rounded-tl', 'rounded-br', 'rounded-bl']],
  ['borderWidth', ['border', 'border-x', 'border-y', 'border-t', 'border-r', 'border-b', 'border-l']],
  ['borderColor', ['border', 'border-x', 'border-y', 'border-t', 'border-r', 'border-b', 'border-l']],
  ['borderOpacity', ['border-opacity']],
  ['backgroundColor', ['bg']],
  ['backgroundOpacity', ['bg-opacity']],
  ['backgroundImage', ['bg']],
  ['gradientColorStops', ['from', 'via', 'to']],
  ['backgroundSize', ['bg']],
  ['backgroundPosition', ['bg']],
  ['fill', ['fill']],
  ['stroke', ['stroke']],
  ['strokeWidth', ['stroke']],
  ['objectPosition', ['object']],
  ['padding', ['p', 'px', 'py', 'pt', 'pr', 'pb', 'pl']],
  ['textIndent', ['indent']],
  ['verticalAlign', ['align']],
  ['fontFamily', ['font']],
  ['fontSize', ['text']],
  ['fontWeight', ['font']],
  ['lineHeight', ['leading']],
  ['letterSpacing', ['tracking']],
  ['textColor', ['text']],
  ['textOpacity', ['text-opacity']],
  ['textDecorationColor', ['decoration']],
  ['textDecorationThickness', ['decoration']],
  ['textUnderlineOffset', ['underline-offset']],
  ['placeholderColor', ['placeholder-color']], // placeholder
  ['placeholderOpacity', ['placeholder-opacity']],
  ['caretColor', ['caret']],
  ['accentColor', ['accent']],
  ['opacity', ['opacity']],
  ['boxShadow', ['shadow']],
  ['boxShadowColor', ['shadow']],
  ['outlineWidth', ['outline']],
  ['outlineOffset', ['outline-offset']],
  ['outlineColor', ['outline']],
  ['ringWidth', ['ring']],
  ['ringColor', ['ring']],
  ['ringOpacity', ['ring-opacity']],
  ['ringOffsetWidth', ['ring-offset']],
  ['ringOffsetColor', ['ring-offset']],
  ['blur', ['blur']],
  ['brightness', ['brightness']],
  ['contrast', ['contrast']],
  ['dropShadow', ['drop-shadow']],
  ['grayscale', ['grayscale']],
  ['hueRotate', ['hue-rotate']],
  ['invert', ['invert']],
  ['saturate', ['saturate']],
  ['sepia', ['sepia']],
  ['backdropBlur', ['backdrop-blur']],
  ['backdropBrightness', ['backdrop-brightness']],
  ['backdropContrast', ['backdrop-contrast']],
  ['backdropGrayscale', ['backdrop-grayscale']],
  ['backdropHueRotate', ['backdrop-hue-rotate']],
  ['backdropInvert', ['backdrop-invert']],
  ['backdropOpacity', ['backdrop-opacity']],
  ['backdropSaturate', ['backdrop-saturate']],
  ['backdropSepia', ['backdrop-sepia']],
  ['transitionProperty', ['transition']],
  ['transitionDelay', ['delay']],
  ['transitionDuration', ['duration']],
  ['transitionTimingFunction', ['ease']],
  ['willChange', ['will-change']],
  ['content', ['content']],
]

const twStatics: string[] = [
  'sr-only',
  'not-sr-only',
  'pointer-events-none',
  'pointer-events-auto',
  'visible',
  'invisible',
  'static',
  'fixed',
  'absolute',
  'relative',
  'sticky',
  'isolate',
  'isolation-auto',
  'float-right',
  'float-left',
  'float-none',
  'clear-left',
  'clear-right',
  'clear-both',
  'clear-none',
  'box-border',
  'box-content',
  'block',
  'inline-block',
  'inline',
  'flex',
  'inline-flex',
  'table',
  'inline-table',
  'table-caption',
  'table-cell',
  'table-column',
  'table-column-group',
  'table-footer-group',
  'table-header-group',
  'table-row-group',
  'table-row',
  'flow-root',
  'grid',
  'inline-grid',
  'contents',
  'list-item',
  'hidden',
  'table-auto',
  'table-fixed',
  'border-collapse',
  'border-separate',
  'transform',
  'transform-cpu',
  'transform-gpu',
  'transform-none',
  'touch-auto',
  'touch-none',
  'touch-pan-x',
  'touch-pan-left',
  'touch-pan-right',
  'touch-pan-y',
  'touch-pan-up',
  'touch-pan-down',
  'touch-pinch-zoom',
  'touch-manipulation',
  'select-none',
  'select-text',
  'select-all',
  'select-auto',
  'resize-none',
  'resize-y',
  'resize-x',
  'resize',
  'snap-none',
  'snap-x',
  'snap-y',
  'snap-both',
  'snap-mandatory',
  'snap-proximity',
  'snap-start',
  'snap-end',
  'snap-center',
  'snap-align-none',
  'snap-normal',
  'snap-always',
  'list-inside',
  'list-outside',
  'appearance-none',
  'break-before-auto',
  'break-before-avoid',
  'break-before-all',
  'break-before-avoid-page',
  'break-before-page',
  'break-before-left',
  'break-before-right',
  'break-before-column',
  'break-inside-auto',
  'break-inside-avoid',
  'break-inside-avoid-page',
  'break-inside-avoid-column',
  'break-after-auto',
  'break-after-avoid',
  'break-after-all',
  'break-after-avoid-page',
  'break-after-page',
  'break-after-left',
  'break-after-right',
  'break-after-column',
  'grid-flow-row',
  'grid-flow-col',
  'grid-flow-row-dense',
  'grid-flow-col-dense',
  'flex-row',
  'flex-row-reverse',
  'flex-col',
  'flex-col-reverse',
  'flex-wrap',
  'flex-wrap-reverse',
  'flex-nowrap',
  'place-content-center',
  'place-content-start',
  'place-content-end',
  'place-content-between',
  'place-content-around',
  'place-content-evenly',
  'place-content-stretch',
  'place-items-start',
  'place-items-end',
  'place-items-center',
  'place-items-stretch',
  'content-center',
  'content-start',
  'content-end',
  'content-between',
  'content-around',
  'content-evenly',
  'items-start',
  'items-end',
  'items-center',
  'items-baseline',
  'items-stretch',
  'justify-start',
  'justify-end',
  'justify-center',
  'justify-between',
  'justify-around',
  'justify-evenly',
  'justify-items-start',
  'justify-items-end',
  'justify-items-center',
  'justify-items-stretch',
  'space-y-reverse',
  'space-x-reverse',
  'divide-y-reverse',
  'divide-x-reverse',
  'divide-solid',
  'divide-dashed',
  'divide-dotted',
  'divide-double',
  'divide-none',
  'place-self-auto',
  'place-self-start',
  'place-self-end',
  'place-self-center',
  'place-self-stretch',
  'self-auto',
  'self-start',
  'self-end',
  'self-center',
  'self-stretch',
  'self-baseline',
  'justify-self-auto',
  'justify-self-start',
  'justify-self-end',
  'justify-self-center',
  'justify-self-stretch',
  'overflow-auto',
  'overflow-hidden',
  'overflow-clip',
  'overflow-visible',
  'overflow-scroll',
  'overflow-x-auto',
  'overflow-y-auto',
  'overflow-x-hidden',
  'overflow-y-hidden',
  'overflow-x-clip',
  'overflow-y-clip',
  'overflow-x-visible',
  'overflow-y-visible',
  'overflow-x-scroll',
  'overflow-y-scroll',
  'overscroll-auto',
  'overscroll-contain',
  'overscroll-none',
  'overscroll-y-auto',
  'overscroll-y-contain',
  'overscroll-y-none',
  'overscroll-x-auto',
  'overscroll-x-contain',
  'overscroll-x-none',
  'scroll-auto',
  'scroll-smooth',
  'truncate',
  'text-ellipsis',
  'text-clip',
  'whitespace-normal',
  'whitespace-nowrap',
  'whitespace-pre',
  'whitespace-pre-line',
  'whitespace-pre-wrap',
  'break-normal',
  'break-words',
  'break-all',
  'border-solid',
  'border-dashed',
  'border-dotted',
  'border-double',
  'border-hidden',
  'border-none',
  'box-decoration-slice',
  'box-decoration-clone',
  'bg-fixed',
  'bg-local',
  'bg-scroll',
  'bg-clip-border',
  'bg-clip-padding',
  'bg-clip-content',
  'bg-clip-text',
  'bg-repeat',
  'bg-no-repeat',
  'bg-repeat-x',
  'bg-repeat-y',
  'bg-repeat-round',
  'bg-repeat-space',
  'bg-origin-border',
  'bg-origin-padding',
  'bg-origin-content',
  'object-contain',
  'object-cover',
  'object-fill',
  'object-none',
  'object-scale-down',
  'text-left',
  'text-center',
  'text-right',
  'text-justify',
  'align-baseline',
  'align-top',
  'align-middle',
  'align-bottom',
  'align-text-top',
  'align-text-bottom',
  'align-sub',
  'align-super',
  'uppercase',
  'lowercase',
  'capitalize',
  'normal-case',
  'italic',
  'not-italic',
  'normal-nums',
  'ordinal',
  'slashed-zero',
  'lining-nums',
  'oldstyle-nums',
  'proportional-nums',
  'tabular-nums',
  'diagonal-fractions',
  'stacked-fractions',
  'underline',
  'overline',
  'line-through',
  'no-underline',
  'decoration-solid',
  'decoration-double',
  'decoration-dotted',
  'decoration-dashed',
  'decoration-wavy',
  'antialiased',
  'subpixel-antialiased',
  'bg-blend-normal',
  'bg-blend-multiply',
  'bg-blend-screen',
  'bg-blend-overlay',
  'bg-blend-darken',
  'bg-blend-lighten',
  'bg-blend-color-dodge',
  'bg-blend-color-burn',
  'bg-blend-hard-light',
  'bg-blend-soft-light',
  'bg-blend-difference',
  'bg-blend-exclusion',
  'bg-blend-hue',
  'bg-blend-saturation',
  'bg-blend-color',
  'bg-blend-luminosity',
  'mix-blend-normal',
  'mix-blend-multiply',
  'mix-blend-screen',
  'mix-blend-overlay',
  'mix-blend-darken',
  'mix-blend-lighten',
  'mix-blend-color-dodge',
  'mix-blend-color-burn',
  'mix-blend-hard-light',
  'mix-blend-soft-light',
  'mix-blend-difference',
  'mix-blend-exclusion',
  'mix-blend-hue',
  'mix-blend-saturation',
  'mix-blend-color',
  'mix-blend-luminosity',
  'outline-none',
  'outline',
  'outline-dashed',
  'outline-dotted',
  'outline-double',
  'outline-hidden',
  'ring-inset',
  'filter',
  'filter-none',
  'backdrop-filter',
  'backdrop-filter-none',
]

const twExcludes: string[] = [
  'accent-auto',
]

function normalizeConfig(obj: any, master?: Record<string, any>) {
  master = master ?? obj
  const newObj: any = {}
  Object.keys(obj).forEach((key) => {
    let value = master?.[key]
    while (typeof value === 'function') {
      value = value({
        theme: (what: string, d: string) => master?.[what] ?? d,
      })
    }
    newObj[key] = value
  })
  return newObj
}

const normalized = normalizeConfig(twTheme)

const twClasses: string[] = []

Object.keys(normalized).forEach((key) => {
  const value = normalized[key]
  if (value && typeof value !== 'string') {
    const parents = twThemeMapping.find(x => x[0] === key)?.[1] ?? [key]
    parents.forEach((parent) => {
      Object.keys(value).forEach((subKey) => {
        const token = `${parent}-${subKey}`
          .replace(/-DEFAULT$/g, '')
          .replace(/[a-z][A-Z]/g, u => `${u[0]}-${u[1].toLowerCase()}`)
        twClasses.push(token)
      })
    })
  }
})

export const twTargetDynamic = twClasses.filter(c => !twExcludes.includes(c))
export const twTargetStatic = twStatics.filter(c => !twExcludes.includes(c))
